---
title: "DS301_HW1"
author: "Aashwin Lamsal"
date: "2/2/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## HW #1 Problem 3a
```{r}
library(jtools) #necessary to create a table for our summary output
#reading Toluca.txt and placing into a variable
toluca = read.table("Toluca.txt", header = T) #Header is true since we have a header in our dataset

#head(toluca) # used to check if the data was read in properly

#Fitting a simple linear regression model: x= lotSize, y= workHrs

x = toluca$lotSize
y = toluca$workHrs
fit = lm(y~x)
summary = summary(fit) #summary of the output

summ(fit) #used for jtools table output

```
From the summary output:

Beta-naught = 62.37
Beta_one = 3.57
se(Beta-naught) = 26.18
se(Beta-one) = 0.35
Beta-naught p-value = 0.0259 approximately 0.03
Beta-one p-value = 4.45e-10 approximately 0.00

## HW #1 Problem 3b

```{r}
#Drawing scatterplot of workHrs versus lotSize
#Reestablishing x and y variables, and creating the fitted simple linear regression model
x = toluca$lotSize
y = toluca$workHrs
fit = lm(y~x)
#summary(fit) was used to double check that I got the same results as 3a

#Scatterplot creation
plot(x,y, main = "Toluca Work Hours vs. Lot Size", pch = 16, xlab = "Lot Size", ylab = "Work Hours")
abline(fit) #adding least squares line

```

## HW #1 Problem 3c
```{r}
#Reestablishing x and y variables, and creating the fitted simple linear regression model
x = toluca$lotSize
y = toluca$workHrs
fit = lm(y~x)

#names(fit) used to see names of the different attributes in the model

firstFiveFittedValues = fit$fitted.values[1:5]
firstFiveResidualValues = fit$residuals[1:5]

cat("The first 5 fitted values are as follows: \n", firstFiveFittedValues)

cat("\n \n The first 5 residual values are as follows: \n", firstFiveResidualValues)




```
##                      1 2 3 4 5
## Fitted Values   347.982





